-- 코드를 입력하세요
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND PUBLISHED_DATE >= DATE '2021-01-01' AND PUBLISHED_DATE < DATE '2022-01-01'
ORDER BY PUBLISHED_DATE;